# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Molecular Quantum Mechanics (CB2070)
author: Patrick Norman
logo: logo.png
exclude_patterns       : [ README.md, labs/* ]
only_build_toc_files   : false

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/kthpanor/cb2070
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

html:
  use_issues_button: true
  use_repository_button: true
  favicon: favicon.png
